#include "game/state.hpp"

int State::days;
int State::hero;
int State::rank;
int State::difficulty;
int State::contract;
int State::continent;
int State::score;
int State::gold;
int State::leadership;
int State::permanent_leadership;
int State::commission;
int State::spell_power;
int State::known_spells;
int State::max_spells;
int State::followers_killed;
int State::weeks_passed;
int State::days_passed_this_week;
int State::boat_x;
int State::boat_y;
int State::boat_c;
bool State::magic;
bool State::siege;
bool State::boat_rented;
bool State::combat;
std::array<bool, 26> State::visited_castles;
std::array<int, 14> State::spells;
std::array<std::vector<unsigned char>, 4> State::visited_tiles;
std::array<int, 5> State::army;
std::array<int, 5> State::counts;
std::array<int, 5> State::morales;
bool State::auto_move;
glm::ivec2 State::auto_move_dir;
std::array<const unsigned char *, 4> State::tiles;
int State::x;
int State::y;
int State::timestop;
std::array<std::array<Mob, 40>, 4> State::mobs;
std::array<std::vector<int>, 4> State::friendly_mobs;
std::array<bool, 17> State::villains_found;
std::array<bool, 17> State::villains_captured;
std::array<bool, 4> State::sail_maps_found;
std::array<bool, 4> State::continent_maps_found;
std::array<int, 26> State::castle_occupants;
std::array<std::array<int, 5>, 26> State::garrison_armies;
std::array<std::array<int, 5>, 26> State::garrison_counts;
std::array<std::array<int, 5>, 26> State::castle_armies;
std::array<std::array<int, 5>, 26> State::castle_counts;
std::array<glm::ivec2, 3> State::sail_map_tiles;
std::array<glm::ivec2, 4> State::continent_map_tiles;
std::array<std::array<glm::ivec2, 2>, 4> State::teleport_cave_tiles;
std::array<std::vector<ShopInfo>, 4> State::shops;
std::array<TownGen, 26> State::towns;
std::array<bool, 8> State::artifacts_found;
